// <auto-generated />
using System;
using Kayak.DataAccess.UserPermission.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kayak.DataAccess.DeviceData.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20241019053915_kayak_11")]
    partial class kayak_11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.32");

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Component_Device");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.DeviceAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthConfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GatewayId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Component_DeviceAccess");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.DeviceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthConfig")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Component_DeviceConfig");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.DeviceGateway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GatewayTypeValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NetWorkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtocolCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Component_DeviceGateway");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnProtocolCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceTypeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtocolCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Component_DeviceType");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.EventConfigure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataTypeValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Eventlevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Expands")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Physical_EventConfigure");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.FunctionConfigure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Expands")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputIds")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAsync")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Physical_FunctionConfigure");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.NetworkLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NetworkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NetworkType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.Property<int>("logLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sys_NetworkLog");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.NetworkPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClusterModeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentTypeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Delimited")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableSSL")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("EnableSwagger")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("EnableTLS")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("EnableWebService")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FixedLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsMulticast")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxMessageLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<int?>("ResolveMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleScript")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Component_NetworkPart");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.OperateLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RunTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sys_OperateLog");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Component_Product");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsChildren")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Component_ProductCategory");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.PropertyConfigure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataTypeValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadWrite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<string>("SourceValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("Step")
                        .HasColumnType("REAL");

                    b.Property<string>("UnitValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueRange")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Physical_PropertyConfigure");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.PropertyThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<string>("ThresholdLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThresholdType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThresholdValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Physical_PropertyThreshold");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.Protocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnProtocol")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtocolCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<string>("Script")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Component_Protocol");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.RegistryCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegistryCenterType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Component_RegistryCenter");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.ReportProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Device_ReportProperty");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.ReportPropertyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThresholdType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sys_ReportPropertyLog");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.SysDataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DefaultVaule");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Sys_DataType");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.SysDictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Code");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsShow")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsShow");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("ParentCode")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ParentCode");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Sys_Dictionary");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.SysOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contacter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LevelCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SysOrgType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sys_Organization");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.SysUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Sys_Unit");
                });

            modelBuilder.Entity("Kayak.DataAccess.DeviceData.Entities.SysUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlipayToken")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Creater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("QQToken")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("QRCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RealName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("Remark");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updater")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeChatToken")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sys_User");
                });
#pragma warning restore 612, 618
        }
    }
}
